// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMV4k_3WnxI_ewaWSXRDgZCqDV4m-IevE',
    appId: '1:993624332604:web:1f9363950e844ec70c2639',
    messagingSenderId: '993624332604',
    projectId: 'mangazone-73666',
    authDomain: 'mangazone-73666.firebaseapp.com',
    storageBucket: 'mangazone-73666.firebasestorage.app',
    measurementId: 'G-1PLG8SH6Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEInsj010TgSWNC_qHwnTamWjAPylTyis',
    appId: '1:993624332604:android:8b84ab5ee56c21260c2639',
    messagingSenderId: '993624332604',
    projectId: 'mangazone-73666',
    storageBucket: 'mangazone-73666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTKXUJ8YEGtRJ2f1u2eJ-l-vTxG_9fSY',
    appId: '1:993624332604:ios:d0caf9d3d06c0af90c2639',
    messagingSenderId: '993624332604',
    projectId: 'mangazone-73666',
    storageBucket: 'mangazone-73666.firebasestorage.app',
    iosBundleId: 'com.example.mangazone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTKXUJ8YEGtRJ2f1u2eJ-l-vTxG_9fSY',
    appId: '1:993624332604:ios:d0caf9d3d06c0af90c2639',
    messagingSenderId: '993624332604',
    projectId: 'mangazone-73666',
    storageBucket: 'mangazone-73666.firebasestorage.app',
    iosBundleId: 'com.example.mangazone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMV4k_3WnxI_ewaWSXRDgZCqDV4m-IevE',
    appId: '1:993624332604:web:c5d2ec2ab73bbaa20c2639',
    messagingSenderId: '993624332604',
    projectId: 'mangazone-73666',
    authDomain: 'mangazone-73666.firebaseapp.com',
    storageBucket: 'mangazone-73666.firebasestorage.app',
    measurementId: 'G-28V9VC0769',
  );
}
